// This file is automatically generated. Do not edit it directly.
import { createClient, type SupabaseClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

const missingConfig = [
  !SUPABASE_URL?.trim() && 'VITE_SUPABASE_URL',
  !SUPABASE_PUBLISHABLE_KEY?.trim() && 'VITE_SUPABASE_PUBLISHABLE_KEY',
].filter(Boolean);

export const supabaseConfigError = missingConfig.length
  ? `Configuracao do Supabase ausente: ${missingConfig.join(', ')}.`
  : null;

export const isSupabaseConfigured = supabaseConfigError === null;

function createUnavailableClient(): SupabaseClient<Database> {
  return new Proxy({}, {
    get(_target, property) {
      if (property === 'then') return undefined;
      throw new Error(supabaseConfigError ?? 'Supabase nao configurado.');
    },
  }) as SupabaseClient<Database>;
}

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = isSupabaseConfigured
  ? createClient<Database>(SUPABASE_URL.trim(), SUPABASE_PUBLISHABLE_KEY.trim(), {
      auth: {
        storage: localStorage,
        persistSession: true,
        autoRefreshToken: true,
      },
    })
  : createUnavailableClient();
